
== Persistent Storage

IMPORTANT: Le système de fichiers des conteneurs ne permet pas de persister les
données au-delà de la durée de vie du conteneur. Ce système de fichiers est
réinitialisé à chaque destruction du conteneur.

[TIP]
====
Il faut utiliser les volumes pour persister les données. Les volumes sont des
espaces de stockage virtuels gérés par Docker et qui se trouvent donc sur
l'hôte. Ils permettent donc

* Au conteneur de "commniquer" avec l'hôte
* à différents conteneurs de communiquer entre eux
====

[NOTE]
====
Les volumes permettent donc deux patterns très intéressants : le polymorphisme
et la composition

. Le polymorphisme est possible du fait que l'on peut garder le même conteneurs
avec des volumes différents et donc des données et des usages différents

. La composition se réalise par la communication inter conteneurs permise par
les volumes.
====

=== Création de volumes

[source, bash]
....
docker run -it --name listing.4.1 \
-v /volumeExample busybox:latest /bin/sh -c 'ls /'
....

=== Communication avec l'hôte

Il y a deux types de volumes essentiellement :

. Docker Managed Volumes
. Bind Mount Volumes

==== Docker Managed Volumes

.Entrée
....
$ docker inspect listing.4.1
....

.Sortie
....
...
"Volumes": {
"/workspace":












"/mnt/sda1/var/lib/docker/vfs/dir/7e2edb4a1ddd7b2cddd60b1ac104d5d6469e9df8449389bd
a047b2fce0c031ca"
},
...
....

Donc, chaque volume est système de fichier virtuel (vfs) géré par Docker dans
`/mnt/sda1/var/lib/docker/vfs/...` qui est monté dans le conteneur comme indiqué
lors de la création de conteneur.

==== Bind Mount Volumes

.Entrée
....
$ docker run --name listing.4.2 \
-v /volume1 -v /volume2 -v /anotherVolume \
busybox:latest \
echo "This container has multiple Docker managed volumes."

$ docker inpect listing.4.2
....

.Sortie
....
...
"Volumes": {
"/anotherVolume":
"/mnt/sda1/var/lib/docker/vfs/dir/c98056a56e40d3ae7b80bf7da81ecffcaadc70f58802a
3a2908e24f58a9c30a2",
"/volume1":
"/mnt/sda1/var/lib/docker/vfs/dir/6f92a91b594bed84ebe3a6d2c91308681a3ba3c3c77b4
aab5b8c115e6fe969c1",
"/volume2":
"/mnt/sda1/var/lib/docker/vfs/dir/262f169812956b3b6015478f5e7a4555816dd036fa404
1517678096e9304b47a"
},
...
....

===== Création d'un conteneur avec un Bind Mount Volume
[source, bash]
....
# create a host directory
$ mkdir ./listing.4.3

# bind mount the directory and create an empty file
$ docker run --name listing.4.3 \
  -v "$(pwd)"/listing.4.3:/workspace \ //<1>
  busybox:latest \
  touch /workspace/evidence //<2>

# check out the result
$ ls ./listing.4.3
....
<1> Le volume est indiqué avec une paire `host_abs_path:container_mount_point`.
Tout à la fin de la ligne, on indique la commande à exécuter dans le conteneur.
<2> Commande à exécuter dans le container après son chargement. Cette commande
crée donc le fichier `evidence` dans le volume `workspace`

===== Le contenu du volume remplace le contenu présent dans l'image
(polymorphisme)
[source, bash]
....
docker run --name pauls_web \
  -v /home/paul/www:/usr/local/apache2/htdocs/ \ //<1>
  httpd:latest
....
<1> Le contenu du dossier `/home/paul/www` du host va remplacer ce qui se trouve
dans `/usr/local/apache2/htdocs/` par défaut au niveau de l'image.

NOTE: Le dossier est créé dans le conteneur s'il n'existe pas. S'il existe, sont
contenu est remplacé par le contenu du dossier chargé en tant que volume.

===== Variante avec chargement en lecture seule
[source, bash]
....
docker run --name pauls_web \
  -v /home/paul/www:/usr/local/apache2/htdocs/:ro \ //<1>
  httpd:latest
....
<1> Rajout de `:ro` pour *Read-Only* juste après l'association
`dossier_local:mount_point:options`

===== Monter un fichier seul (et non un dossier)
[source, bash]
....
# create a file to mount
ls –l > directoryListing.txt

docker run --rm \
  –v "$(pwd)"/directoryListing.txt:/some/path/listing \ //<1>
  busybox:latest cat /some/path/listing
....
<1> Il suffit d'indiquer un fichier au lieu d'un dossier dans la première partie
de l'option `-v` pour qu'uniquement le fichier `directoryListing.txt` soit
chargé en tant que volume.

=== Sharing Volumes

Il y a deux façons de partager des volumes

. Partage naïf
. Partage personnalisé

==== Naive Sharing

[source, bash]
....
# create a new directory
mkdir listing.4.5

# generates some logs from a container
docker run --name listing.4.5.alpha -d \
  -v "$(pwd)"/listing.4.5:/data allingeek/ch4_writer_a

# view the logs from another container
docker run --rm \
  -v "$(pwd)"/listing.4.5:/data //<1>
  busybox:latest head /data/logA

# view the logs from the host
cat ./listing.4.5 /logA

# stop the log generator
docker kill listing.4.5.alpha
....
<1> Le deuxième conteneur monte le Bind Volume créé pour l'autre conteneur.

NOTE: Cette façon de charger un volume présente l'avantage de la flexibilité du
point de montage comme le montre l'exemple suivant :

[source, bash]
....
# start the first writer
docker run --name listing.4.6.alpha -d \
  -v "$(pwd)"/listing.4.6:/data allingeek/ch4_writer_a

# start the second writer
docker run --name listing.4.6.beta -d \
  -v "$(pwd)"/listing.4.6:/data allingeek/ch4_writer_b

# start the watcher
docker run --rm \
  -v "$(pwd)"/listing.4.6:/towatch:ro //<1>
  usybox:latest head /towatch/logA
....
TIP: On peut spécifier un point de montage différent et un mode d'accès au
volume
différent des autres, ce qui n'est pas possible avec l'option `--volumes-from`
présenté par la suite.

==== Generalized Sharing and the `--volumes-from` Flag

NOTE: Utilisation de l'option `--volumes-from` pour charger dans le conteneur
créé tous les autres volumes possédés par un autre conteneur.

===== Syntaxe de base
[source, bash]
....
docker run --volumes-from <source_container> --name new_container [...] image
....

[WARNING]
.Limitations
====
. Les volumes chargés depuis un autre conteneurs auront le même point de
montage.
. Si deux conteneurs sources possèdent des volumes qui sont montés au même
endroit, il y aura conflit et uniquement le dernier va l'emporter.
. Il n'est pas possible de spécifier un mode d'accès différent que celui défini
dans le volume du conteneur d'origine.
====


=== The Managed Volume Life Cycle

Il n'est pas toujours facile de savoir comment supprimer un volume géré par
Docker, surtout si celui-ci est orphelin (n'est possédé par aucun conteneur).


==== Volume Ownership
NOTE: Un conteneur possède tous les volumes gérés par Docker qu'il a montés

==== Cleaning Up Volumes (page 59)
Pour éviter de créer des volumes orphelins, il faut les supprimer lorsqu'on
supprimer le conteneur qui le possède.

[source, bash]
....
docker rm -v <container>
....


.Explication
NOTE: L'option `-v` de la commande `docker rm` demande de supprimer tous les
volumes qui sont associés au conteneur à supprimer. Les volumes qui sont
partagés avec d'autres conteneurs ne sont pas supprimés, mais un compteur de
référence est décrémenté.

=== Volume Container Pattern

TIP: Pour gérer de manière plus efficace les volumes, on peut les organiser en
créant un conteneur qui n'a d'autre but que de les contenir. Il est ainsi
possible de distribuer via des conteneurs des fichiers de configuration pour
d'autres ceonteneurs.

WARNING: Je ne suis pas certain que cette pratique fasse l'unanimité. Le but
d'un conteneur est finalement de pouvoir être utilisé tel quel sans trop de
bidouillage. C'est peut-être utile dans certaines architectures très complexes
pour des  besoins très spéficiques.

==== Keeping Volumes Organized

==== Volume Mount Points as Interface Contract

==== Data Packed Volume Containers


.Building a data packed volume container
[source, bash]
....

# create a volume container from an image with specific content
docker run --name 4.8.packed \
  –v /config \
  allingeek/ch4_packed /bin/sh -c ‘cp /packed/* /config/’

# list the material copied into the volume from a different container
docker run --rm --volumes-from 4.8.packed \
  busybox:latest /bin/sh –c ‘ls /config’

# view the available material from a different container
docker run --rm --volumes-from 4.8.packed \
  busybox:latest /bin/sh –c ‘cat /config/packedData’

# Remember to use –v when you clean up
docker rm -v 4.8.packed
....

=== Polymorphic Container Pattern

=== Résumé

Volumes are powerful. They poke holes in containers, allowing files to be shared with the
host or other containers.

* Volumes are parts of the host file system that are mounted into containers at specified
locations.

* There are two types of volumes: Docker managed volumes that are located in the
Docker part of the host file system, and bind mounted volumes that are located
anywhere on the host file system.

* Volumes have life cycles that are independent of any specific container, but Docker
managed volumes can only be referenced with a container handle.

* Volumes allow the host and containers to focus on their distinct concerns.

* The orphan volume problem can make disk space difficult to recover. Use the -v option
on docker rm to avoid the problem.

* The volume container pattern is useful for keeping your volumes organized and avoiding
the orphan volume problem.

* The data packed volume container pattern is useful for distributing static content for
other containers.

* The polymorphic container pattern is a way to compose minimal functional components
and maximize reuse.
